---
apiVersion: v1
data:
  client-info.yaml: |- {{- dict "clients" $.Values.connections | toYaml | b64enc | nindent 4 }}
kind: Secret
metadata:
  labels: {{- include "synology-csi.labels" $ | nindent 4 }}
  name: {{ include "synology-csi.fullname" $ }}-client-info
