apiVersion: v2
description: A Helm chart to install an openvpn server inside a kubernetes cluster.  Certificate
  generation is also part of the deployment, and this chart will generate client keys
  as needed.
name: openvpn
version: 1.0.0
appVersion: 2.5.0
icon: https://forums.openvpn.net/styles/openvpn/theme/images/ovpnlogo.png
keywords:
- openvpn
- vpn
- tunnel
- network
- service
- connectivity
- encryption
home: https://openvpn.net/index.php/open-source.html
sources:
- https://github.com/lovellfelix/openvpn-docker
- https://lovellfelix.github.io/helm-charts/openvpn
- https://github.com/lovellfelix/helm-charts
