
{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "nodejs.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nodejs.metaLabels" . | nindent 4 }}
{{- if .Values.metrics.enabled }}
    prometheus: {{ .Values.metrics.prometheusInstance }}
{{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nodejs.selectorLabels" . | nindent 6 }}
  endpoints:
{{- if .Values.metrics.endpoints }}
{{ toYaml .Values.metrics.endpoints | indent 4 }}
{{- else }}
  - path: {{ .Values.metrics.endpointPath | default "/metrics" }}
    interval: {{ .Values.metrics.endpointInterval | default "15s" }}
    targetPort: {{ .Values.metrics.endpointTargetPort | default 5000 }}
    honorLabels: {{ .Values.metrics.endpointHonorLabels | default true }}
{{- end }}
{{- end }}